name: mobile_app
description: A Flutter application with clean architecture, localization, and environment management.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Navigation
  go_router: ^12.1.1

  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Error Handling
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Environment
  flutter_dotenv: ^5.1.0

  # Storage
  shared_preferences: ^2.2.2

  # Utilities
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.1

  # JWT
  dart_jsonwebtoken: ^2.12.2

  # Barcode & File Management
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  # PDF Preview
  syncfusion_flutter_pdfviewer: ^30.1.40

  # UI
  cupertino_icons: ^1.0.6
  flutter_advanced_switch: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1

  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

  # Linting
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  image_path: "assets/images/logo_with_background.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/env/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
